Pythia EvtGen interface
key4hep/k4SimDelphes pull request #25
Opened 2021-02-08 10:36 UTC by mchrzasz

2021-02-09 08:58 UTC, tmadlener requested changes
Hi @mchrzasz

Thanks for opening this. I haven't yet tested it, but I had a look at the code and I have added a few comments requesting some small changes.

From the looks of it the `PythiaEvtGen_Interface` class does not depend on anything from key4hep, so this can probably be moved quite easily in the end, right? Or did I miss something here?

2021-02-15 15:37 UTC, vvolkl commented
Thanks @mchrzasz for the PR and @tmadlener for the comments. I mostly think that there are still some tests needed, but I propose to merge this now and adress the comments in a future PR.

2021-02-15 16:10 UTC, clementhelsens commented
@vvolkl we should not merge now, @mchrzasz is fixing an issue that I discovered when trying to decay Bc hadrons. in this case the generation needs to be done until a ccbar pair is produced at ME level

2021-02-22 09:51 UTC, mchrzasz commented
Hey,

Yes I think I will fix the ccbar issue today with all other comments.

2021-02-24 13:29 UTC, mchrzasz commented on standalone/src/PythiaEvtGen_Interface.cc
> +  delete pythia;
Yes you are right. The ownership is not transferred. I have deleted this deletion :)

2021-02-24 14:02 UTC, mchrzasz commented on standalone/src/DelphesPythia8EvtGenReader_k4Interface.h
> +class DelphesPythia8EvtGenReader: public DelphesInputReader {
Yes, you are totally right :) Changed to DelphesPythia8EvtGenReader_k4Interface

2021-02-24 15:25 UTC, mchrzasz commented on standalone/src/PythiaEvtGen_Interface.h
> +  int **signal_map;
Changed to vector of vectors.

2021-02-24 15:25 UTC, mchrzasz commented on standalone/src/PythiaEvtGen_Interface.cc
> +  signal_map= new int*[NOfSignal];
This is obsolete now with the vector of vectors.

2021-02-24 15:25 UTC, mchrzasz commented on standalone/src/PythiaEvtGen_Interface.cc
> +  delete signal_map;
Correct. Now it's gone

2021-02-24 16:02 UTC, tmadlener reviewed
Hi @mchrzasz thanks for the fixes and updates. I have two additional comments, that are a bit nit-picky and do not necessarily have to go into this version, but can also be fixed later.

If I understand correctly now also the ccbar issue that @clementhelsens mentioned, right? For me this is good to be merged as it is, but I will let him comment, on whether everything works as expected right now.

2021-02-24 16:29 UTC, mchrzasz commented on standalone/src/PythiaEvtGen_Interface.cc
> +  evtgen = new EvtGen(decayfile.c_str(), pdl.c_str(), eng, radCorrEngine, &extraModels);
I think (to be checked) that EvtGen doesn't take the ownership. So indeed I can change to unique pointer.
About the ccbar: not yet. Next commit will fix that :) Will let you know

2021-02-24 17:14 UTC, clementhelsens commented on standalone/src/PythiaEvtGen_Interface.cc
> +  evtgen = new EvtGen(decayfile.c_str(), pdl.c_str(), eng, radCorrEngine, &extraModels);
@tmadlener , Marcin, just ping me when the changes for c flavour hadrons is there and I can  give it a try

2021-02-25 12:00 UTC, vvolkl commented
Thanks everyone, I'm going to merge this now as we want to do a build that includes all edm4hep covariance matrix fixes.

2021-02-25 12:01 UTC, merged

2021-02-25 13:01 UTC, mchrzasz commented
I will now create a 2nd PR. I have just finished testing the ccbar solution. it's very simple fix so I would merge it as well.