Apply changes from upstream delphes: renaming DelphesHepMCReader -> DelphesHepMCReader2
key4hep/k4SimDelphes pull request #57
Opened 2021-06-02 08:06 UTC by vvolkl

Normally, I'd try to keep backward compatibility, but due to all the breaking changes in the trackcovariance code, that won't be possible anyway.

BEGINRELEASENOTES
- Apply changes from upstream delphes: renaming DelphesHepMCReader -> DelphesHepMCReader2

ENDRELEASENOTES

2021-06-02 08:15 UTC, vvolkl commented
However, since there is the issue of https://github.com/delphes/delphes/pull/97 in the delphes master, maybe we wait and I switch delphes to 3.4.3pre11 in the nightlies?

2021-06-02 08:21 UTC, tmadlener commented
This looks good to me. For full compatibility with delphes we would probably also have to rename our `DelphesHepMC_EDM4HEP` to `DelphesHepMC2_EDM4HEP`, but I think that is too much.

3.4.3pre11 should still work, so we could use that for the nightlies. In the end, I think we have to follow delphes here probably, but I would wait until that has stabilized again, there was quite a bit of development there in the past few weeks. In any case for a k4SimDelphes release we will need a stable delphes release to depend on.

2021-06-15 13:26 UTC, tmadlener approved these changes
Now that we have delphes 3.5.0 this also looks good to me.

2021-06-15 14:08 UTC, tmadlener requested changes

2021-06-15 14:08 UTC, tmadlener commented on standalone/src/DelphesHepMCReader.h
> +#include "classes/DelphesHepMCReader2.h"
The `2` seems to be at the wrong place here, it should be the following:
```suggestion
#include "classes/DelphesHepMC2Reader.h"
```

2021-06-15 14:08 UTC, tmadlener commented on standalone/src/DelphesHepMCReader.h
> +    m_reader = new DelphesHepMCReader2;
```suggestion
    m_reader = new DelphesHepMC2Reader;
```

2021-06-15 14:08 UTC, tmadlener commented on standalone/src/DelphesHepMCReader.h
> +  DelphesHepMCReader2 *m_reader = 0;
```suggestion
  DelphesHepMC2Reader *m_reader = 0;
```

2021-06-16 14:28 UTC, merged